error: introduce ERROR_INJECTED
It's a simple way to check if a boolean error injection is set.

Needed-for tarantool/tarantool-ee#1919

NO_DOC=internal
NO_TEST=internal
NO_CHANGELOG=internal