Fix build
checkpoint_delete isn't available in 1.10, use checkpoint_destroy
instead.

 | src/box/memtx_engine.c:638:2: error: implicit declaration of function 'checkpoint_delete' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
 |         checkpoint_delete(ckpt);
 |         ^

Fixes commit 8fd63f37c544 ("memtx: cancel checkpoint thread at exit").