config: allow empty configuration file
Before this patch, Tarantool, when started with empty configuration
file, used to fail with a non verbose error:
```
$ ./src/tarantool -n instance-001 -c single.yaml
LuajitError: [cluster_config] Unexpected data type for a record: "nil"
fatal error, exiting the event loop
```

Now Tarantool instance can be set up with configuration from remote
configuration sources available in Tarantool Enterprise Edition and
run with empty config file. When there is no configuration provided
for the instance an according error is thrown.

Closes #9845

NO_DOC=bugfix

(cherry picked from commit 369c255b9721a9ffd2fd6cb8296f376558c35b60)