test: fix number to string conversion in tuple format map test
Though the range of values of the number being converted to string in the
tuple format map test never exceeds 10, GCC 12 issues warnings about the
size of the buffer to which the string version of the number is written:

NO_WRAP
```
test/unit/tuple_format_map.c:256:53: error: ‘%zu’ directive output may be truncated writing between 1 and 19 bytes into a region of size 4 [-Werror=format-
truncation=]
  256 |                 snprintf(name, lengthof(name), "test%zu", i);
      |                                                     ^~~
test/unit/tuple_format_map.c:256:48: note: directive argument in the range [0, 9223372036854775807]
  256 |                 snprintf(name, lengthof(name), "test%zu", i);
      |                                                ^~~~~~~~~
test/unit/tuple_format_map.c:256:17: note: ‘snprintf’ output between 6 and 24 bytes into a destination of size 8
  256 |                 snprintf(name, lengthof(name), "test%zu", i);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
NO_WRAP

Let's make GCC happy and increase all the buffer sizes to 32.

NO_CHANGELOG=<build fix>
NO_DOC=<build fix>
NO_TEST=<build fix>