bitset: fix compilation on macOS 12
Asserts are disabled in the Release build, that leads to:

$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-Werror
$ make

[ 43%] Building C object src/lib/bitset/CMakeFiles/bitset.dir/bitset.c.o
src/lib/bitset/bitset.c:169:9: error: variable 'cardinality_check' set but not used [-Werror,-Wunused-but-set-variable]
        size_t cardinality_check = 0;
               ^

NO_DOC=build fix
NO_TEST=build fix
NO_CHANGELOG=build fix

(cherry picked from commit a6b76abdd21792ef56629c61bafff0dc86ca57bb)