error: use int64_t as reference counter
Before it was unsafe to use error.prev, box.error.last(), or any error
method that increments error reference counter. Any of them could throw a
Lua error in case of INT32_MAX overflow.

This patch uses int64_t as error reference counter making it impossible
to get counter overflow.

Closes #4902

(cherry picked from commit 2e3c81deea505cb5a03d606de7373bb41b559cd9)