ci: fix sending failure message for fuzzing
Call the `checkout` action with the `path` param to avoid the following
error:

  Error: File was unable to be removed Error: EACCES: permission denied,
  unlink '/home/runner/work/tarantool/tarantool/build-out/csv_fuzzer'

NO_DOC=ci
NO_TEST=ci
NO_CHANGELOG=ci

(cherry picked from commit fe5785bbab93035be8bebf4f49a78e1c0a7c54a7)