error: drop OOM hanldling
Since the commit 5a031fb6ea25 ("exception: drop OOM handling") we
use xmalloc for allocating exceptions so we don't need to check
for NULL.

NO_TEST=refactoring
NO_CHANGELOG=refactoring
NO_DOC=refactoring