ci: fix fail on artifact upload to S3 for freebsd
This patch fixes the following issue:

    Error: Unable to retrieve job ID by provided job name

The `${{ github.job }} (${{ join(matrix.*, ', ') }})` expression was
evaluated to `freebsd (Object)` instead of proper job name. It looks
like the ChristopherHX/github-act-runner agent has a bug somewhere.
Now the job name is made manually to bypass the issue.

NO_DOC=ci
NO_TEST=ci
NO_CHANGELOG=ci