coro: build fix on recent gcc
Build is failed on recent gcc. __regparm__ attribute is for x86-32 only
and we do not support it (at least Tarantool fails to compile for x86-32
currently). So let's just remove this optimization.

```
In file included from /home/shiny/dev/tarantool/src/lib/core/fiber.h:50,
                 from /home/shiny/dev/tarantool/src/on_shutdown.c:35:
/home/shiny/dev/tarantool/third_party/coro/coro.h:380:1: error: ‘regparm’ attribute ignored [-Werror=attributes]
  380 | coro_transfer (coro_context *prev, coro_context *next);
      | ^~~~~~~~~~~~~
```

NO_TEST=build fix
NO_CHANGELOG=build fix
NO_DOC=build fix

(cherry picked from commit ebac0b8c07a64311232cc2824a3aa42899840e6d)