error: added new injection for replication testing
Turning it on makes `box.info.replication` to format
`upstream.peer` URI with all parameters.

The feature is required for test purposes to examine
actual replication peer parameters and compare them
with configured ones.

Part of tarantool/tarantool-ee#1680

NO_DOC=internal
NO_CHANGELOG=internal