ci: fix module API publish job (again)
The new version of the publishing action leads to the following error:

NOWRAP
```
Error: File not found: '/home/runner/work/_actions/JamesIves/github-pages-deploy-action/v4.6.6/lib/main.js'
```
NOWRAP

Let's revert it to v4.6.4 (because v4.6.5 change was reverted in v4.6.6).

See also https://github.com/JamesIves/github-pages-deploy-action/issues/1697

NO_DOC=no code changes
NO_CHANGELOG=see NO_DOC
NO_TEST=see NO_DOC

(cherry picked from commit 7cf41a1bb9b3f0a2eac82c296a764688f5d8b35c)