box: build fix with recent gcc/glibc
There are couple of errors like below and assertions where '=' is
used instead of '=='

```
/home/me/dev/tarantool/src/box/memtx_sort_data.c: In function ‘memtx_sort_data_filename’:
/home/me/dev/tarantool/src/box/memtx_sort_data.c:136:26: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  136 |         char *snap_ext = strrchr(snap_filename, '.');
```

NO_TEST=build fix
NO_CHANGELOG=build fix
NO_DOC=builg fix