error: change file macro to path
Due to a build is going as out-of-source after the patch
781fd38, where was deleted the path of a source dir, macro __FILE__
leads to the compilation fail on ubuntu_21_04. Change __FILE__ to the
file path.

Needed for: #5825

(cherry picked from commit eb3f949411d5e67bd8b264154ad83b23e71530f1)