datetime: refactored new() and set() - part 1
`datetime.new()` and `datetime_object:set()` code
refactored for more clarity.

Deduplicated ymd and hms fields extract.

The test `app-luatest/console_debugger_session_test.lua` fixed
due to changes of `new()` code line, which is used in the test.

Also, the `w` command fixed. Debugger output before fix:
```
luadebug> w
Error: command 'w' expects argument, but none received.
```

Debugger output after fix:
```
luadebug> w 0
 673=>     local h, m, s, hms = extract_obj_hms(obj)
```

NO_DOC=refactoring
NO_CHANGELOG=refactoring
NO_TEST=refactoring

(cherry picked from commit 57cb1f312f85a38a9d554f6d97959ecf2088e85e)