lib: fix build error with fresh gcc compiler
Build start to fail with my distro's new gcc version 15.1.1:

```
in file included from /home/shiny/dev/tarantool/src/lib/tzcode/localtime.c:18:
/home/shiny/dev/tarantool/src/lib/tzcode/tzfile.h:25:15: error: initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (2> 1 chars into 20 available) [-Werror=unterminated-string-initialization]
   25 | #define TZDIR "/usr/share/zoneinfo" /* Time zone object file directory */
      |               ^~~~~~~~~~~~~~~~~~~~~
/home/shiny/dev/tarantool/src/lib/tzcode/localtime.c:310:46: note: in expansion of macro ‘TZDIR’
  310 | static char const tzdirslash[sizeof TZDIR] = TZDIR "/";
      |
/home/shiny/dev/tarantool/test/unit/uuid.c:125:41: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (7 chars into 6 available) [-Werror=unterminated-string-initialization]
  125 |                                 .node = "Ad\325,b\353"},
      |                                         ^~~~~~~~~~~~~~
/home/shiny/dev/tarantool/test/unit/uuid.c:131:41: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (7 chars into 6 available) [-Werror=unterminated-string-initialization]
  131 |                                 .node = "v\025Oo9I"},
      |                                         ^~~~~~~~~~~
/home/shiny/dev/tarantool/test/unit/uuid.c:141:41: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (7 chars into 6 available) [-Werror=unterminated-string-initialization]
  141 |                                 .node = "Ad\325,b\353"},
      |                                         ^~~~~~~~~~~~~~
/home/shiny/dev/tarantool/test/unit/uuid.c:147:41: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (7 chars into 6 available) [-Werror=unterminated-string-initialization]
  147 |                                 .node = "v\025Oo9I"},
      |
```

NO_TEST=build fix
NO_CHANGELOG=build fix
NO_DOC=build fix

(cherry picked from commit 53fd97d5e58c9865f0cd31c5a9f3d8e525dcef8f)