test: fix flaky gh_8121_memtx_mvcc_stream_test
The test checks that replication stream doesn't get transaction
conflict errors. However, currently it fails with the following
error: "attempt to index field 's' (a nil value)", where 's' is
a space, created at master during before_all phase.

The problem is the fact, that the test doesn't wait for replica
to be synchronized with master before dropping the replication
source. So, sometimes replica doesn't have any space 's' at the
beginning of the test body execution.

Let's add waiting for vclocks synchronization before reconfiguring
box.cfg.replication on replica.

Closes tarantool/tarantool-qa#311

NO_CHANGELOG=test
NO_DOC=test