say: replace panic macro with a function
This patch refactors the panic macro into a function to prevent
preprocessor conflicts. Previously, the panic macro in
`src/lib/core/say.h` could clash with LuaJIT's internal panic routine,
causing macro expansion issues and compilation failures. By using a
function instead, the patch resolves these conflicts and ensures
correct handling of panic calls.

Example of error:

Let’s assume we have the following situation in `say.h`:

```c
// say.h
...
...
```

And we have the following code in `another.c` that includes this header:

```c
// another.c
...
{
    global_State *g = G(L);
    ...
    // Try to call g->panic.
    // The preprocessor will replace g->panic with the panic macro, which will cause an error.
    g->panic("An error occurred!");
    ...
}
...
```

When you try to compile this code, you will get the following
compilation error:

```bash
error: ‘struct global_State’ has no member named ‘fprintf’
   xxx |     g->panic("An error occurred!");
```

Closes #5365

NO_DOC=refactoring
NO_TEST=refactoring
NO_CHANGELOG=refactoring