lua: fix breakage triggered by LuaJIT
The LuaJIT commit ("FFI: Turn FFI finalizer table into a proper
GC root.") broke Tarantool build:

```
/__w/luajit/luajit/src/lua/utils.c: In function ‘luaL_pushcdata’:
[ 66%] Building C object src/CMakeFiles/server.dir/lua/tnt_datetime.c.o
/__w/luajit/luajit/src/lua/utils.c:132:18: error: ‘CTState’ {aka ‘struct CTState’} has no member named ‘finalizer’
  132 |    GCtab *t = cts->finalizer;
      |                  ^~
```

The patch fixes that.

Follows up of #10199

NO_CHANGELOG=building
NO_DOC=building
NO_TEST=building