ci: use actions/checkout@v3.1.0 with FreeBSD
ChristopherHX/github-act-runner@0.4.1, which we use on FreeBSD,
is incompatible with newest actions/checkout@v3.2.0, aliased to @v3.
Until this is resolved, FreeBSD workflows will use fixed version
actions/checkout@v3.1.0.

actions/checkout@v3.2.0 fails with an unclear error:

> ⭐  Run actions/checkout@v3
>   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
> Error: Unable to resolve v3: unsupported object type
> Error: Unable to resolve v3: unsupported object type
> Error:   ❌  Failure - actions/checkout@v3
> Error: unsupported object type

NO_DOC=CI
NO_TEST=CI
NO_CHANGELOG=CI

(cherry picked from commit a79d32b107d7958a772c11fc739c36ec0c1e571e)