error: add GaiError class for getaddrinfo errors
The constructor takes gai error code and converts it to an error
message. It also clears saved_errno, which is set by SystemError,
because it doesn't make sense for gai errors, and updates
SystemError::log to skip strerror() if saved_errno is 0.

This will allow us to return detailed error messages in case an error
can come both from getaddrinfo or e.g. socket:

  if (err->saved_errno != 0)
      return strerror(err->saved_errno);
  else
      return err->errmsg;

(Before this patch this wouldn't work, because we set saved_errno to EIO
for getaddrinfo errors.)

Note about the Lua socket module - some its users might expect errno set
to EIO if socket.getaddrinfo fails. At least, test/app/socket.test.lua
relies on that. So let's set errno to EIO if socket.getaddrinfo fails
for backward compatibility.