build: drop unused variable detected by clang 15
```
<...>/src/box/sql/vdbe.c:378:11: error: variable 'nVmStep' set but not
    used [-Werror,-Wunused-but-set-variable]
        unsigned nVmStep = 0;      /* Number of virtual machine steps */
                 ^
```

The usage of the variable was removed in commit dbad19ef0aae ("sql: drop
unused functions").

See also #8110.

NO_DOC=no user visible behavior changes
NO_TEST=see NO_DOC
NO_CHANGELOG=dbad19ef0aae is not released yet