build: fix rpm packages build on Fedora 32
Tarantool packages build scenario at rpm/tarantool.spec
installs Python packages for Tarantool testing. In some
latest OS like Fedora 32 old Python packages based on
Python 2 version were deprecated and changed to Python 3.
Currently Tarantool testing based on Python 2 which
packages stored at local backport repository and it
should be used from there calling it as python2-* packages.

Issue:
...
No matching package to install: 'python-yaml >= 3.0.9'
...
Not all dependencies satisfied
Error: Some packages could not be found.

Needed for #4599
Closes #4965

(cherry picked from commit b304a78df0f8d900136c47dc3945061115382805)