static build: fix build on ubuntu
Fixed static build with '-DBUILD_STATIC=ON' option:

* Added cmake option CMAKE_DL_LIBS to icu library for
  test/unit tests binaries builds at file:
    cmake/FindICU.cmake
  due to fail:
    [ 84%] Linking CXX executable vy_point_lookup.test
    /usr/local/lib/libicuuc.a(putil.ao): In function `uprv_dl_open_62':
    putil.cpp:(.text+0x1a22): undefined reference to `dlopen'
    /usr/local/lib/libicuuc.a(putil.ao): In function `uprv_dlsym_func_62':
    putil.cpp:(.text+0x1a7d): undefined reference to `dlsym'
    /usr/local/lib/libicuuc.a(putil.ao): In function `uprv_dl_close_62':
    putil.cpp:(.text+0x1a61): undefined reference to `dlclose'
    collect2: error: ld returned 1 exit status

* Added cmake option CMAKE_DL_LIBS to gomp library for
  test/unit tests binaries builds at file:
    cmake/BuildMisc.cmake
  due to fail:
    [ 91%] Linking CXX executable bps_tree.test
    /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.a(target.o): In function `gomp_target_init':
    (.text+0x8b): undefined reference to `dlopen'
    (.text+0xa2): undefined reference to `dlsym'
    (.text+0xd9): undefined reference to `dlclose'
    (.text+0x29b): undefined reference to `dlsym'
    (.text+0x2a8): undefined reference to `dlerror'
    (.text+0x2d0): undefined reference to `dlsym'
    (.text+0x2e9): undefined reference to `dlsym'
    (.text+0x300): undefined reference to `dlsym'
    (.text+0x317): undefined reference to `dlsym'
    (.text+0x330): undefined reference to `dlsym'
    /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.a(target.o):(.text+0x34d): more undefined references to `dlsym' follow
    /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.a(target.o): In function `gomp_target_init':
    (.text+0x9cc): undefined reference to `dlerror'
    collect2: error: ld returned 1 exit status

Close #5024

(cherry picked from commit 2e8fa27ab35c2e4b1b32cdc3613e1e538e1cf414)
(cherry picked from commit 4f424bee0a75d841866390643f8a68519c7a342d)