ci: fix building Alpine packages
* Update build-time and run-time dependencies.

* Support build with gc64 enabled.

* Disable sysprof due to the following error while building:

NO_WRAP
  ```
  <...>/third_party/luajit/src/lj_sysprof.c:29:10: fatal error: execinfo.h: No such file or directory
    29 | #include <execinfo.h>
       |
  ```
NO_WRAP

* Update .pack.mk to set package version in the case of a git tag to the
  following format:

    2.11.0[_<release type>]

  Where `<release type>` is `alpha1`, `beta1`, `rc1`, etc.
  Note, we have an extra logic when the git tag is `x.x.x-entrypoint`.
  Alpine build system doesn't support package name with such kind of
  version and that's why we use `alpha0` instead of `entrypoint`.
  See for details [1].

* Update .pack.mk to set package version in the other cases to the
  following format:

    2.11.0_<release type>_p<N>

  Where `<release type>` is `alpha1`, `beta1`, `rc1`, etc and `<N>` is
  the patch number after the latest release. Unfortunately, we cannot
  use the similar version pattern that we use for dev DEB/RPM packages
  (`2.11.0_<release type>.<N>.dev`) because Alpine build system doesn't
  support it. Plus, we have the same logic for `entrypoint` here.
  See for details [1].

[1] https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#pkgver

Part of tarantool/tarantool-qa#266

NO_DOC=ci
NO_TEST=ci
NO_CHANGELOG=ci