Fix FreeBSD build
Fixed swim headers in addition to commit:
88892f13a3934c72721e6240bfa5fe174d62d99b ('swim: fix build on FreeBSD')

Included unistd.h header to fix the following errors:

In file included from src/lib/swim/swim_transport_udp.c:31:
src/lib/swim/swim_transport.h:61:1:
    error: unknown type name 'ssize_t'; did you mean 'size_t'?
ssize_t
^~~~~~~
size_t
/usr/include/netinet6/in6.h:698:18: note: 'size_t' declared here
typedef __size_t        size_t;
                        ^
In file included from src/lib/swim/swim_transport_udp.c:31:
src/lib/swim/swim_transport.h:66:1:
    error: unknown type name 'ssize_t'; did you mean 'size_t'?
ssize_t
^~~~~~~
size_t
/usr/include/netinet6/in6.h:698:18: note: 'size_t' declared here
typedef __size_t        size_t;

Closes #4050

(cherry picked from commit c2e824841cf0407aba94a6ae191c89449b6d3f4e)