zlib: bump version to 1.3.1
zlib 1.3.1 is required by Arrow libraries used in Tarantool EE, besides
this version fixes the following OS X compilation error:
NO_WRAP
```
In file included from tarantool/build/zlib-prefix/src/zlib/zutil.c:10:
In file included from tarantool/build/zlib-prefix/src/zlib/gzguts.h:21:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:61:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:322:7: error: expected identifier or '('
  322 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
tarantool/build/zlib-prefix/src/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Library/Developer/CommandLineTools/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^

```
NO_WRAP

NO_DOC=dependency update
NO_TEST=dependency update
NO_CHANGELOG=dependency update

(cherry picked from commit 7c0637e74807de41970915108c09545825ea6add)