error: finish changes to several C modules to use box.error
We already do some steps to use box.error in these C modules. Let's
finish it to make a clear distinction between C modules that are
switched to box.error and that are not.

Follow-up #9996

NO_CHANGELOG=internal
NO_DOC=internal