build: fix build fail on clang 15
Fixed pthread-related CMake checks. The checks code is built with
`-pedantic-errors` and it leads to errors of the following kind on
clang 15:

```
<...>/CMakeFiles/CMakeScratch/TryCompile-78KaOK/src.c:4:17: error: a
    function declaration without a prototype is deprecated in all
    versions of C [-Werror,-Wstrict-prototypes]
        int main() { pthread_setname_np(pthread_self(), ""); }
                ^
                 void
```

See commit 1c6b6f85f4d3 ("build: fix build fail on clang 15") for the
SQL related changes. They're not included into the 1.10 backport.

1.10 has a specific problem, which is fixed here as well:

```
<...>/src/fiber_pool.c:49:53: error: passing arguments to
    'fiber_is_cancelled' without a prototype is deprecated in all
    versions of C and is not supported in C2x
    [-Werror,-Wdeprecated-non-prototype]
        while (!stailq_empty(output) && !fiber_is_cancelled(fiber())) {
                                                           ^
<...>/src/fiber_pool.c:77:25: error: passing arguments to
    'fiber_is_cancelled' without a prototype is deprecated in all
    versions of C and is not supported in C2x
    [-Werror,-Wdeprecated-non-prototype]
        if (!fiber_is_cancelled(fiber()) && (msg != NULL ||
```

The fix is a partial backport of commit dddcb18cd232 ("fiber: use void
for empty args").

See also https://github.com/tarantool/small/issues/57

Fixes #8110

NO_DOC=build fix
NO_TEST=build fix

(cherry picked from commit 1c6b6f85f4d36787f9e0a861a5437412e65bae11)