build: fix static build error when compiling with Clang on Linux
This patch fixes the following error when building tarantool statically
with Clang compiler on a Linux system:

    error: argument unused during compilation: '-static-libstdc++'

Fixes #9646

NO_DOC=build issue
NO_TEST=build issue
NO_CHANGELOG=build issue

(cherry picked from commit 64afe49b0bfad574b2e769cb5052cb6cd2e0a3b9)