uuid: use snprintf instead of sprintf
This patch fixes compilation on macOS 12.6.3 with AppleClang 14.0.0:

$ cmake .. -DENABLE_WERROR=ON
$ cmake --build .

[ 47%] Building CXX object src/box/CMakeFiles/tuple.dir/tuple_compare.cc.o
src/box/tuple_compare.cc:31:
src/box/tuple_compare.h:38:
src/box/tuple.h:37:
src/tt_uuid.h:127:2: error: 'sprintf' is deprecated: This function
is provided for compatibility reasons only. Due to security concerns
inherent in the design of sprintf(3), it is highly recommended that
you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
        sprintf(out, "%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x",
        ^

In Tarantool 2.x this is fixed by commit 368766e697fd ("Fix static buffer
align").

Closes #8277

NO_DOC=build fix
NO_TEST=build fix
NO_CHANGELOG=build fix