tests: suppress message 'Broken pipe exception handling'
Message below is printed every time on shutdown `httpd.py` when
`test/app-luatest/http_client_test.lua` is running by luatest without
capturing stdout:

```
BrokenPipeError: [Errno 32] Broken pipe exception handling
```

The patch suppress this exception by adding a handler for a signal
`SIGPIPE`.

NO_CHANGELOG=testing
NO_DOC=testing
NO_TEST=testing

(cherry picked from commit 8912df258f794562afff0c72c63f383472c9e37b)