datetime: fix unit test for older GCC version
This commit fixes the following error on centos 7 gcc:
```
./test/unit/datetime.c:422:10:
error: missing initializer for field ‘nsec’ of
‘struct datetime’ [-Werror=missing-field-initializers]
struct datetime date = { 0 };
```

The fix is using full struct initialization:
`struct datetime date = { 0, 0, 0, 0 };`
Instead of:
`struct datetime date = { 0 };`

NO_CHANGELOG=test fix for CI
NO_DOC=test fix for CI