mp_error: rename mp_sizeof_error to mp_sizeof_error_one
The function doesn't iterate over the stack of errors so it should have
suffix '_one', like mp_encode_error_one.