error: use error_payload to store optional members
error_payload is a part of struct error now. All the fields stored
in C++ classes on top of struct error are moved into the payload.

Part of #5568
Part of #4610
Part of #4907